# Generated by Django 4.0.5 on 2023-01-27 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=500)),
                ('eventCity', models.CharField(max_length=100)),
                ('eventOrganizer', models.CharField(max_length=100)),
                ('eventPrice', models.IntegerField(max_length=100)),
                ('eventImage', models.CharField(default='https://cdn.pixabay.com/photo/2016/11/18/17/47/iphone-1836071_960_720.jpg', max_length=600, null=True)),
            ],
        ),
    ]
