# Generated by Django 4.0.5 on 2023-01-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_event_eventprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='eventType',
            field=models.CharField(default='misc', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventImage',
            field=models.CharField(default='https://cdn.pixabay.com/photo/2016/11/18/17/47/iphone-1836071_960_720.jpg', max_length=600),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventOrganizer',
            field=models.CharField(max_length=200),
        ),
    ]
